### ISSUE TITLE
Radxa Zero 3W status

### ISSUE THREAD

**Issue by Gurkengewuerz** [JohnDGodwin/OpenIPC_Groundstations#1]
Hey,

i am wondering what the status of the Radxa Zero 3W development is because you are releasing an image but say "In Development" in the readme.

Also i would like to know what hardware combination you have tested. Radxa Zero (how much RAM?) + RTL8812AU?
How well is it running?

Thanks and greetings from Germany.

**Comment by JohnDGodwin** [comment]
I'm running the 4GB RAM / 32 GB eMMC variation of the board. I have it still under development because the software for this board is still very new and it is not performing up to my standards for fpv drone flying. 
That being said it is functional on my board at the very least, running WFB-ng and RTL8812AU drivers and gstreamer.

**Comment by JohnDGodwin** [comment]
Removing DVR from the gstreamer pipeline speeds up latency quite a bit, It may be asking too much from the board.

**Comment by Gurkengewuerz** [comment]
Thank you for the clarification. So my guess is you are using an Orange Pi 5 Plus as groundstation?
Because you are saying "my standards for fpv drone flying" with what do you compare it? Do you have any comparison with the popular NVR Bord Hi3536?

**Comment by JohnDGodwin** [comment]
The NVR only displays 60fps max out of it's HDMI port.
The Orange Pi 5 Plus is a better ground station -- the processor is better, the software is more developed, and it does at least 120fps out the hdmi port.
I fly both DJI O3 and HDZero systems normally, and I'm using the HDZero goggles HDMI input 720p100 from the Orange Pi 5 Plus for these projects.

**Comment by Gurkengewuerz** [comment]
Alright that seems fair. Thanks :)

**Comment by Gurkengewuerz** [comment]
FYI I ordered a 3W 4GB/32GB eMMC, and I am waiting for the [OpenIPC AIO](https://store.openipc.org/OpenIPC-AIO-v1-0-UltraSight-Enthusiast-Edition-p49287054). I will use a Skyzone SKY04X Pro with 720p@100fps for testing.

**Comment by JohnDGodwin** [comment]
I look forward to your testing, I have a stream-only image available now. Still working on DVR.
