### ISSUE TITLE
 Unable to display image

### ISSUE THREAD

**Issue by Linjieqiang** [JohnDGodwin/OpenIPC_Groundstations#2]
Hello, I burned your image into my development board and connected it to the network as required. There is also data connection, but the image cannot be displayed in HDMI. What step did I make wrong?

![ae86bdb34965f443560e03d593daedb](https://github.com/JohnDGodwin/OpenIPC_Groundstations/assets/10217966/f346e61e-1f77-4812-9b54-80c9338dc6f6)

![image](https://github.com/JohnDGodwin/OpenIPC_Groundstations/assets/10217966/fe590a77-683f-475e-b163-eecb12252db0)

**Comment by JohnDGodwin** [comment]
Do you have a push button installed between pins 9 and 11?


![20240309_050922](https://github.com/JohnDGodwin/OpenIPC_Groundstations/assets/35317840/ff5725fe-89ff-4fa6-8e2f-b572ba45c8c2)

**Comment by JohnDGodwin** [comment]
I'm currently working on a new image that will automatically start the stream, while the button controls just dvr.
<br>
[You can find it soon here.](https://github.com/OpenIPC/sbc-groundstations)

**Comment by JohnDGodwin** [comment]
New image has been uploaded at the link provided. Please use that with the provided instructions.

**Comment by Linjieqiang** [comment]
Will try. Thanks~

**Comment by Linjieqiang** [comment]
![image](https://github.com/JohnDGodwin/OpenIPC_Groundstations/assets/10217966/074e29e2-861e-4da5-874e-010edf4984de)

@JohnDGodwin https://github.com/OpenIPC/sbc-groundstations/releases/tag/orangepi5plus-v1.0.0 I used the same hardware and configuration, but I got this result. Is there anything wrong?

**Comment by Linjieqiang** [comment]
> Do you have a push button installed between pins 9 and 11?
> 
> ![20240309_050922](https://private-user-images.githubusercontent.com/35317840/311430046-ff5725fe-89ff-4fa6-8e2f-b572ba45c8c2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMzc4MDMsIm5iZiI6MTcxMDAzNzUwMywicGF0aCI6Ii8zNTMxNzg0MC8zMTE0MzAwNDYtZmY1NzI1ZmUtODlmZi00ZmE2LThlMmYtYjU3MmJhNDVjOGMyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDAyMjUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNzM5ODQ3NWM0MGYyYjlhNjMxN2Q5M2MwM2EwZjFhNzFmZjYwZmU4MGI4NzBjMWJiZGRjYTZkZjlhNTFiZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E81n5miWz940A7oE18i-oNE0sSw01wimNm2XzoO1A5c)

But I try your method, it works~!

**Comment by JohnDGodwin** [comment]
Are you having issues with the new image? Did you transfer new keys?

**Comment by Linjieqiang** [comment]
I used the same hardware to test. The old image can display the image normally by triggering PIN9 and PIN11. But when I use the new image, the above prompt will appear. What I can confirm is that I have uploaded gs.key through SSH.

![image](https://github.com/JohnDGodwin/OpenIPC_Groundstations/assets/10217966/bcb9b0b8-d876-42cd-ab62-780a949ffb8c)
Incredibly, with this configuration, the latency of 1080P is as low as 62ms. It’s amazing... thank you for your efforts. Next I will try to use the RK3566 chip combined with your image for testing, which can reduce the cost of use. I was wondering how I can contact you? Via discord?

**Comment by Linjieqiang** [comment]
Off topic, I want to buy a Radxa Zero 3w development board next. What configuration do you think I should choose? Is 2GB of memory enough? And how much capacity is required for EMMC? Do you think it would be suitable for flying fpv? Not sure how much worse its decoding speed is than the RK3588

**Comment by JohnDGodwin** [comment]
I am on Discord if you want to talk further, my username is johhngoblin
